// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWDMmM7aWJhvJeekXneadyhtThFAo1YsM',
    appId: '1:516743015485:web:4283e8f267cd56f2954e54',
    messagingSenderId: '516743015485',
    projectId: 'mawjood-application',
    authDomain: 'mawjood-application.firebaseapp.com',
    storageBucket: 'mawjood-application.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO7Tgn0UlC735XlyGpJrb2rEd8Xw5gAW4',
    appId: '1:516743015485:android:f8dcb1e3717816d5954e54',
    messagingSenderId: '516743015485',
    projectId: 'mawjood-application',
    storageBucket: 'mawjood-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-GaYC5XK9FJHvdnlWryiDf8NNn3ZDuMA',
    appId: '1:516743015485:ios:b688010cc2c9a763954e54',
    messagingSenderId: '516743015485',
    projectId: 'mawjood-application',
    storageBucket: 'mawjood-application.appspot.com',
    iosBundleId: 'com.example.mawjoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-GaYC5XK9FJHvdnlWryiDf8NNn3ZDuMA',
    appId: '1:516743015485:ios:eedbe0ff1bbb68fb954e54',
    messagingSenderId: '516743015485',
    projectId: 'mawjood-application',
    storageBucket: 'mawjood-application.appspot.com',
    iosBundleId: 'com.example.mawjoodApp.RunnerTests',
  );
}
